### ISSUE TITLE
Feature request: have an issue number #1000

### ISSUE THREAD

**Issue by thaJeztah** [docker/fig#1000]
Fingers crossed :smile:

**Comment by aanand** [comment]
Can't reproduce.

**Comment by thaJeztah** [comment]
Strange, neither can I :wink:

Guess it's time for :cake: then, to celebrate the occasion.

**Comment by aanand** [comment]
![13024_l](https://cloud.githubusercontent.com/assets/1062/6331298/463bce74-bb76-11e4-89a8-98fbb95f27f1.jpg)
