### ISSUE TITLE
Can I change container name?

### ISSUE THREAD

**Issue by pahaz** [docker/fig#431]
I have two projects.
One `/home/app1/source` and `/home/app2/source`.

And both containers have same name `source_web_1`, and after `fig up` start only one of them.
How to fix it?

**Comment by thaJeztah** [comment]
@kcmerrill unfortunately, at this stage, this is not possible. Fig relies on the `projectname_servicename_xx` convention to find which containers belong to a project. It's a "hack" and the maintainers are well aware of that. Work is in progress "upstream" in docker to add meta-data to containers, which will allow more flexible naming.

Having said that, I think the original question was answered and this issue can be closed, @dnephin ?

**Comment by dnephin** [comment]
Yup, you can use `-p` or `FIG_PROJECT_NAME` to set a project name.

#652 is the issue for explicit names, so I agree we can close.
