### ISSUE TITLE
Fig build fails in folders with names containing capital letters

### ISSUE THREAD

**Issue by nonsensery** [docker/fig#655]
## Steps to Reproduce

1. Create a folder named "FigTest".
2. Add a Dockerfile:
    
    ```
    FROM ubuntu:14.04
    ```
3. Add a fig.yml:
    
    ```
    app:
      build: .
    ```
4. Run `fig build`.

## Expected Result

A container image would be built from the current directory.

## Actual Result

Operation fails with an error from Docker: "Invalid repository name (FigTest_app), only [a-z0-9-_.] are allowed"

## Discussion

It looks like Docker image names do not allow uppercase letters. Fig creates the image name from the name of the directory, with some processing to remove invalid characters, but it does not convert uppercase letters to lowercase.

**Comment by lwansbrough** [comment]
Update on this? Kind of annoying! :)

**Comment by Powpow-Shen** [comment]
@lwansbrough 
Indeed.

**Comment by sethherr** [comment]
+1 :cake:

**Comment by danroberts** [comment]
+1 Also, apparently if you change the name of the folder from capital to lowercase there are times were fig still chooses the capital version for some reason. That part may be unique to my setup, but it's super annoying.

**Comment by aanand** [comment]
Closed by https://github.com/docker/fig/pull/568

**Comment by aanand** [comment]
Anyone experiencing this issue is encouraged to give Compose 1.1.0 RC2 a try! https://github.com/docker/fig/releases/tag/1.1.0-rc2
