### ISSUE TITLE
Command line -e flag causes an error when fig.yml has a list of environment variables

### ISSUE THREAD

**Issue by totallymike** [docker/fig#703]
When environment variables are configured in the fig.yml file like so:

```yml
environment:
  - MIX_ENV=test
```

running `fig run -e MIX_ENV=dev` causes python to throw up because it tries to treat the environment options like a dictionary instead of a list.

Translating the environment settings to:

```yml
environment:
  MIX_ENV: test
```

resolves the error.

The relevant line in the source is [cli/main.py#318](https://github.com/docker/fig/blob/master/fig/cli/main.py#L318).

**Comment by dnephin** [comment]
Looks like there are a few issues open for this, going to close this for #927
