### ISSUE TITLE
2 dockerfiles: one for production and one for development?

### ISSUE THREAD

**Issue by olalonde** [docker/fig#797]
I have the following problem. My web front end uses a node.js process during development (enabling live reload, etc.) and in production, I only serve a pre-build `dist/` folder using Nginx.

What would be the best way to handle this? I have come up with 2 options. Have a different Dockerfile for production and development. In that case, my question is how can I specify which one to use in my `fig.yml` file? The other option would be to use two different virtual hosts in my nginx config but in that case, the development domain would still be accessible in production if someone else knows it. Another solution would be to tell Nginx which config file to use based on an environment variable, but I'm not sure how to do that.

**Comment by SvenDowideit** [comment]
I think this could be based off https://github.com/docker/docker/pull/9707

**Comment by SvenDowideit** [comment]
What I do today (without fig), is to make one base image that does the common work, and then I build that with a tag. then both the prod and dev Dockerfiles have `FROM mybase`

wrt ENV var based - you could have an ENTRYPOINT script that uses the ENV var to copy one or the other file into the nginx.conf dir before it starts nginx.

**Comment by olalonde** [comment]
> wrt ENV var based - you could have an ENTRYPOINT script that uses the ENV var to copy one or the other file into the nginx.conf dir before it starts nginx.

Sounds like a good idea, thanks.

**Comment by crosbymichael** [comment]
#9707 was merged and it should provide the ability to do what you need.

**Comment by ohord** [comment]
Well as #9707 introduces -f flag thus fig should support custom Dockerfile in fig.yml. Shouldn't it?
