### ISSUE TITLE
Proposal: Make it possible to use "_" in container name

### ISSUE THREAD

**Issue by skolodyazhnyy** [docker/fig#799]
Hi,

Is it possible to allow some word separator in service names? For example I have a service, it's database and database volume containers. These services have names: `service`, `servicedatabase` and `servicedatabasedata`. You can easily identify that `servicedatabase` belongs to `service`, as it has prefix. But because neither '_' nor '-' are allowed these names are super hard to read quickly. So, it will be great if you will allow underscores, so my containers will become: `service`, `service_database` and `service_database_data`

If underscores will be allowed you still will be able to split joined name back to project-name, service-name and instance-number. You can forbid underscore in project name and last part is always an integer, so to split it back you need to cut part before first `_` and after last `_`, these will be project name and instance number the rest is service name.

Thanks a lot!

**Comment by skolodyazhnyy** [comment]
PS. `myproject_serviceDatabaseData_1` looks extremely ugly, it should be either snake_case or camelCase, but not both at the same time.

**Comment by aanand** [comment]
Hmm. I see the argument, but I'm wary of making the logic more complicated - it's already an ugly hack.

Once Docker has queryable container metadata (https://github.com/docker/docker/pull/9882), we can relax naming rules a lot more without fear of breaking stuff.

**Comment by skolodyazhnyy** [comment]
Sounds like a plan, thanks for your answer

**Comment by aanand** [comment]
See https://github.com/docker/compose/issues/1519
