### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by aanand** [docker/fig#806]
Future versions of Fig are going to be rebranded to fit alongside the suite of Docker orchestration tools (the other ones currently being Machine and Swarm). The new name is Compose.

A number of things need to be done to make this happen:

- [ ] Rename the GitHub project
- [ ] Create a new PyPi package
- [ ] Rename the Python module
- [ ] Rename the `fig` executable to `compose` (see below)
  - [ ] Python stub at `bin/fig`
  - [ ] Binaries built by `script/build-osx` and `script/build-linux`
  - [ ] Update the Dockerfile
- [ ] Rename `fig.yml` to `compose.yml`
- [ ] Deprecate `FIG_*` environment variables, introduce `COMPOSE_*` equivalents
- [ ] Update name in docs, including all instances of:
  - [ ] `fig` executable
  - [ ] `fig.yml`
  - [ ] “Fig”
- [ ] Move docs over to docs.docker.com
  - [ ] Convert markup
  - [ ] Rejig it for the CSS
- [ ] Update name in `README.md`, `ROADMAP.md` and `CONTRIBUTING.md`
- [ ] Remove rebranding plans from `ROADMAP.md` 
- [ ] Check that we haven’t messed up the word “config” (or any of its derivatives) anywhere

## Executable name

For now, the executable will be named `compose` for consistency with `machine` and `swarm`. In future, orchestration tools might move to Git-style subcommands (e.g. `docker compose`), at which point we’ll be freer to pick an easier-to-type shorthand. In any case, executable naming is a discussion to be had at a wider scope than just Compose.

**Comment by Waitfish** [comment]
nice work！

**Comment by allengaller** [comment]
It just fit!

**Comment by allengaller** [comment]
nice work！

**Comment by bfirsh** [comment]
See also https://github.com/docker/fig/pull/804

**Comment by bfirsh** [comment]
Looks good.

 - I would suggest we create a new PyPi package and leave the old one intact to not break dependencies. I'm not sure it's even possible to rename PyPi packages anyway.
 - We should consider whether `compose.yml` should have the word "Docker" in it at all.

**Comment by lePoxy** [comment]
Any due date for the 1.1.0 ? I was hoping a new release in order to use envfile and dns-search options, but with the rebrand this will take longer.

**Comment by frank-dspeed** [comment]
i am for coding this in nodejs because its distributed style. and because i love nodejs :D.
a complet recode based on existing nodejs docker clients should take not more then a week

**Comment by aanand** [comment]
Replaced by https://github.com/docker/fig/pull/835
