### ISSUE TITLE
[question] fig and swarm

### ISSUE THREAD

**Issue by david-guenault** [docker/fig#857]
I'm curently testing swarm and know that it is in early stage. Using swarm with docker cli work like a charm but when you deal with complex applications it is a pain in the ass to do it with just docker cli. Enter fig. Running complex applications with fig and swarm seems to work (except for link but i can workaround that with dns discovery). just after fig up -d if you issue fig ps it does not answer anything. I think it is related to the way swarm answer to docker ps by prepending the docker hostname to the container name. So fig is unable to see the project containers. Do you plan to fix this (major issue IMO) or wait for docker compose ?

**Comment by thaJeztah** [comment]
I think this is a dup of https://github.com/docker/fig/issues/814 (and related PR: https://github.com/docker/fig/pull/851)

So, work is in progress, but some things still have to be discussed. Hopefully soon!

**Comment by david-guenault** [comment]
Ok thx that is exactly what i was talking about. I close this one
