### ISSUE TITLE
Support fig.yml and show a deprecation warning

### ISSUE THREAD

**Issue by aanand** [docker/fig#864]

**Comment by thaJeztah** [comment]
+1 would be welcome to give me time to update all my repos :)

**Comment by ibnesayeed** [comment]
If there are both `fig.yml` as well as `compose.yml` in the same directory, later should take the precedence. Should the deprecation warning still be shown or can it just be ignored?

**Comment by aanand** [comment]
The `.yaml` support complicates this too. I think my preferred logic would be:

- Try the following filenames until one exists: `docker-compose.yml`, `docker-compose.yaml`, `fig.yml`, `fig.yaml`
- If there's more than one file with any of the above names, explicitly say which one we're using.
- If we're using `docker-compose.yaml`, show the standard nagging message about file extensions.
- If we're using `fig.*`, show a deprecation warning.

**Comment by ibnesayeed** [comment]
I thought the file name will be `compose.yml` instead of `docker-compose.yml`, or may be both. Short names are good unless they create any confusion.

**Comment by aanand** [comment]
Name length is definitely an issue, but I think it's *more* of an issue for the binary - whose name is being typed over and over - than the configuration file.

I don't love `docker-compose` as a binary name, but I don't mind it all as a filename. Indeed, it's a good clue to someone who's just cloned a repository that it uses Docker.

**Comment by ibnesayeed** [comment]
I am not sure why the binary name was chosen to be `docker-compose` instead of just `compose`, was there any name conflict with any existing package?

**Comment by funkyfuture** [comment]
this is getting off-topic:
"[Ecplicit is better than implicit](https://www.python.org/dev/peps/pep-0020/)" is a good mantra.

i suggest you set an `alias` in your `.bashrc` or set a link in your `$PATH`.
though a short form that is canonically used in Docker's community would support communications.
`dco`? `doco`, `docomp`? but anyone who wants to discuss that should create a new issue for that. i don't want to discuss it.

and yes, `pip search compose` actually lists a package.

**Comment by albers** [comment]
I updated the bash completion according to aanands suggestion, see #887.
