### ISSUE TITLE
How to run `fig ps` outisde of the root of a project?

### ISSUE THREAD

**Issue by bitliner** [docker/fig#870]
One nice thing of docker is that you can just run `docker ps` to list every container running on a certain machine.

While fig requires to be in a specific folder.

Is there a way to enable `fig ps`  running on any folder?

Please, in case you plan it as feature, if you can address me on how to add this feature, I would be very glad to give an help.

**Comment by NoumanSaleem** [comment]
You can execute fig commands anywhere, but need to specify the location of your fig file.
> -f, --file FILE
Specify an alternate fig file (default: fig.yml)
http://www.fig.sh/cli.html

`$ fig -f /etc/fig.yml ps`

**Comment by bitliner** [comment]
Sorry but that is bad.
I just want to ssh into my machine and look for running containers.
If I need to know where fig.yml is located, you may agree it becomes a tedious task. Maybe I have more than one only fig.yml, specifying every time the folder name is not so intuitive.

**Comment by dnephin** [comment]
If you're looking for running containers, use `docker ps`. fig/compose is specifically for application groups, so it doesn't make much sense to have it duplicate what `docker ps` is already doing.

"Show all containers created by fig" is not currently possible. It will be possible when docker labels are available and used by fig/compose, but even then I'm not sure it makes much sense.

There has been some discussion in https://github.com/docker/docker/pull/9882 about having `docker ps` support labels directly, so once that's all setup, you'll theoretically be able to do something like `docker ps -f docker.compose`

**Comment by bfirsh** [comment]
As @dnephin said, `docker ps` is what you want :)
