### ISSUE TITLE
Docker Compose Website

### ISSUE THREAD

**Issue by RobLoach** [docker/fig#875]
Now that [Docker Compose *1.1.0-rc1*](https://github.com/docker/fig/releases/tag/1.1.0-rc1)  is out and is no longer named Fig, we should start to think about what will happen to [the Fig.sh website](http://www.fig.sh).

* Move it to a sub-documentation section of https://docs.docker.com ?
* Re-brand the website under http://compose.docker.com ?
* Make a whole new http://fig.sh and deal with moving the domain later on?

**Comment by lePoxy** [comment]
Hello,

I think [this](https://github.com/docker/fig/pull/835#issuecomment-70859463) @aanand [comment](https://github.com/docker/fig/pull/835#issuecomment-70859463) answers your question.

**Comment by bfirsh** [comment]
Yep - this will all move to docker.com and docs.docker.com.

**Comment by RobLoach** [comment]
:+1:
