### ISSUE TITLE
Not using Docker temporary directory

### ISSUE THREAD

**Issue by wernight** [docker/fig#881]
fig seems to use another temporary directory than Docker. Docker's temp can be customized because the files are really large and most of my web servers have a small `/tmp`.

I'd suggest to add an option to customize the temporary directory used by fig; or use the same as Docker.

**Comment by dnephin** [comment]
`fig` does not us a temporary directory at all.  I believe there were issues with dockerd previous to 1.3 where it would ignore `TMPDIR` for some files. Maybe that's the issue?

**Comment by dnephin** [comment]
Actually, I guess `docker-py` does use `tempfile` which respects all of these environment variables: https://docs.python.org/2/library/tempfile.html#tempfile.tempdir

It may be that dockerd is being run with one of those set, but the client (`fig`) is not being run with the same environment variables.

**Comment by wernight** [comment]
Yes I'm running Docker 1.0 so it could be it. Thanks
