### ISSUE TITLE
Unable to install fig as per http://www.fig.sh/install.html on OSX

### ISSUE THREAD

**Issue by js1972** [docker/fig#905]
Running this command gave me permission errors. Using sudo made no difference. But if I changed the script to simply download to my home folder then cp it into /usr/local/bin/fig using sudo it works fine...

**Comment by philostler** [comment]
Is that what you did in the end, just copy the file in? I ask as I'm suddenly getting the same problem, used to work fine for me :confused:

**Comment by aanand** [comment]
This will happen if `/usr/local/bin` isn't writable by you. You can either `chmod`/`chown` it to fix that, or download it elsewhere and `sudo cp` it in.

**Comment by philostler** [comment]
Cheers, that's what I've ended up doing. Odd that I've suddenly started seeing this.... Thanks @aanand
