### ISSUE TITLE
unexpected behavior with volumes

### ISSUE THREAD

**Issue by ariovistus** [docker/fig#936]
I am packaging an app in docker with fig and I specify several volumes in my fig.yml. When I remove the volumes from fig.yml and run fig build; fig up; the volumes are still in my image. I have tried fig build --no-cache to no avail.

Is this expected behavior and/or how do I remove the volumes from the image that fig generates?

**Comment by dnephin** [comment]
This would be fixed by #858

For now the workaround is to `fig rm` the container to clear it out
