### ISSUE TITLE
If you restarting the source container, the linked containers /etc/hosts files is not  automatically updated

### ISSUE THREAD

**Issue by BlackRider97** [docker/fig#981]
please refer docker documentation here https://docs.docker.com/userguide/dockerlinks/
it says that 
If you restart the source container, the linked containers /etc/hosts files will be automatically updated with the source container's new IP address, allowing linked communication to continue.

When I using fig links new IP address of source container is not reflecting in linked container.
`
$ sudo fig --version
fig 1.0.1
`
`
$sudo docker --version
Docker version 1.5.0, build a8a31ef
`

**Comment by thaJeztah** [comment]
Are you able to produce this using docker directly, or does the problem only occur for containers created/managed via Fig?

Also, if possible, could you supply a scenario to reproduce this (as simple as possible)?

Thanks!

**Comment by BlackRider97** [comment]
It was my bad.  `fig restart` is working while I was doing `fig stop` then `fig start`
@thaJeztah  Thanks for your response.

**Comment by thaJeztah** [comment]
@BlackRider97 glad you got it working. Could you close this issue to mark it "resolved"? Thanks!

**Comment by BlackRider97** [comment]
Resolved

**Comment by alexandre-hamelin** [comment]
I believe that Compose should update the IP address of linked lower-level containers even if they are completely stopped, removed and restarted, a few reasons.

1. It would be very useful in the course of active system development where the database container needs to be recreated often, but you do not necessarily want to restart other containers (I have 14-15 higher level app containers), a use case I could imagine is not that uncommon.
1. The name of the newly recreated container is the same as the older one (appname_container_1), so one would expect the new container to be recognized by the others without further action.
1. If it's not automatically updated, the developer has to restart the whole system (i.e. all containers) which is very time consuming.

Updating the source container's IP address in other linked containers would be much more convenient. Should I reopen this issue?

**Comment by thaJeztah** [comment]
@alexandre-hamelin I don't think Fig/Compose has any control over that; Docker itself handles the updating of `/etc/hosts` if a container is restarted; Compose only creates the containers (and links between them) via the Docker API.

**Comment by alexandre-hamelin** [comment]
I could imagine it'd be a nice feature for an orchestration tool.
